name: pulmonary_monitor_app
description: App for monitoring of pulmonary (i.e. respiratory) health build using the CARP Mobile Sensing Framework.
version: 2.0.0
homepage: https://github.com/cph-cachet/pulmonary_monitor_app
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.19.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  # The CARP packages used by the app.
  # carp_core: ^1.8.0
  # carp_mobile_sensing: ^1.12.5
  # carp_context_package: ^1.10.0
  # carp_connectivity_package: ^1.4.0
  # carp_survey_package: ^1.8.0
  # carp_audio_package: ^1.4.0
  # carp_apps_package: ^1.6.0
  # carp_health_package: ^1.8.0
  
  # research_package: ^2.0.0
  # cognition_package: ^1.6.0

  # Packages used by CAMS. For some reason, we need to explicitly depend on them here - otherwise, 
  # the app will not launch even though it does compile.
  battery_plus: ^7.0.0
  # device_calendar: ^4.3.1
  device_info_plus: ^12.1.0
  flutter_local_notifications: ^19.4.2
  location: ^8.0.1
  package_info_plus: ^8.3.1
  permission_handler: '>=11.0.0 <13.0.0'
  shared_preferences: ^2.5.0
  sqflite: ^2.4.2
  # health: ^13.2.0
  # flutter_blue_plus: '>=1.29.0 <3.0.0'

  flutter_launcher_icons: ^0.14.0 # For setting app launch icons. See below.


# Overriding carp libraries to use a local copy for debugging and development.
dependency_overrides:
  carp_core:
    path: ../carp/carp.sensing-flutter/carp_core/
  carp_mobile_sensing:
    path: ../carp/carp.sensing-flutter/carp_mobile_sensing/
  carp_context_package:
    path: ../carp/carp.sensing-flutter/packages/carp_context_package/
  carp_connectivity_package:
    path: ../carp/carp.sensing-flutter/packages/carp_connectivity_package/
  carp_audio_package:
    path: ../carp/carp.sensing-flutter/packages/carp_audio_package/
  carp_survey_package:
    path: ../carp/carp.sensing-flutter/packages/carp_survey_package/
  carp_apps_package:
    path: ../carp/carp.sensing-flutter/packages/carp_apps_package/
  carp_health_package:
    path: ../carp/carp.sensing-flutter/packages/carp_health_package/

  research_package:
    path: ../research.package/  
  cognition_package:
    path: ../cognition_package/  

  # due to this issue https://github.com/builttoroam/device_calendar/issues/586 
  device_calendar:
    git: https://github.com/bardram/device_calendar

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any 
  flutter_lints: any


# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/lungs.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo/cachet_logo.png
   - assets/images/carp_logo_example.png
   - assets/logo/lungs.png
   - assets/images/maui.png
   - assets/images/running.png
   - assets/images/audio.png
   - assets/images/cachet.png
   - assets/images/survey.png
   - assets/images/waving-hand.png
   - assets/images/very-sad.png
   - assets/images/sad.png
   - assets/images/ok.png
   - assets/images/happy.png
   - assets/images/very-happy.png
   - assets/lang/da.json
   - assets/lang/en.json

