name: pulmonary_monitor_app
description: App for monitoring of pulmonary (i.e. respiratory) health build using the CARP Mobile Sensing Framework.
version: 2.0.0
homepage: https://github.com/cph-cachet/pulmonary_monitor_app
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.19.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

# CARP libraries
  carp_serializable: ^2.0.0       # polymorphic json serialization
  # carp_core: ^2.0.0               # the core CARP domain model
  # carp_mobile_sensing: ^0.30.6  # the CARP mobile sensing framework

  # CARP sampling packages
  #carp_connectivity_package: ^0.30.0
  #carp_context_package: ^0.30.1
  #carp_audio_package: ^0.30.0
  #carp_communication_package: ^0.30.0
  #carp_backend: ^0.30.0
  #carp_webservices: ^0.30.0
  # carp_health_package: ^2.0.0

  # research_package: ^2.0.0
  # cognition_package: ^1.6.0

  # Packages used by CAMS. For some reason, we need to explicitly depend on them here.
  # Otherwise, the app will not launch or throws MissingPlugin Exceptions, even though 
  # it does compile. See issue #530
  system_info2: ^4.0.0
  path_provider: ^2.0.0
  sqflite: ^2.2.8                         # For local storage in SQLite DB
  permission_handler: '>=11.0.0 <13.0.0'  # For requesting permissions on Android and iOS
  shared_preferences: ^2.2.0
  # package_info_plus: '>=6.0.0 <10.0.0'
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^21.0.0    # For sending notification on AppTask
  timezone: '>=0.10.0 <0.12.0'            # For collecting time zone information
  flutter_timezone: ^5.0.0                # For getting local time zone for scheduling notifications
  flutter_background: ^1.3.0              # For running background services on Android

  # probe-dependent plugins
  device_info_plus: ^12.1.0
  sensors_plus: ^7.0.0
  battery_plus: ^7.0.0
  pedometer: ^4.0.0       # Step count from local OS
  light: ^5.0.0           # Light sensor
  screen_state: ^5.0.0    # Screen LOCK/ON/OFF

  # For Bluetooth Low Energy (BLE) scanning and connection
  flutter_reactive_ble: ^5.0.0

  # Context package plugins
  location: ^8.0.1
  flutter_activity_recognition: ^4.0.0

  # Communication package plugins
  device_calendar: ^4.3.1 # need to use a forked version of device_calendar - see dependency_overrides below
  another_telephony: ^0.4.0
  call_e_log: ^0.0.4

  # Connectivity package plugins
  connectivity_plus: ^7.0.0    # connectivity events
  network_info_plus: ^7.0.0    # wifi ssid name
  flutter_blue_plus: '>=1.29.0 <3.0.0'  # bluetooth scan
  dchs_flutter_beacon: ^0.6.4  # collecting nearby iBeacon devices

  # Audio/Media package plugins
  flutter_sound: ^9.17.0  # audio probe
  noise_meter: ^5.0.0     # measuring noise level

  # wearable device plugins
  health: ^13.2.0

  # app-specific plugins
  flutter_launcher_icons: ^0.14.0 # For setting app launch icons. See below.



# Overriding carp libraries to use a local copy for debugging and development.
dependency_overrides:
  carp_core:
    path: ../carp/carp.sensing-flutter/carp_core/
  carp_mobile_sensing:
    path: ../carp/carp.sensing-flutter/carp_mobile_sensing/
  carp_context_package:
    path: ../carp/carp.sensing-flutter/packages/carp_context_package/
  carp_connectivity_package:
    path: ../carp/carp.sensing-flutter/packages/carp_connectivity_package/
  carp_communication_package:
    path: ../carp/carp.sensing-flutter/packages/carp_communication_package/
  carp_audio_package:
    path: ../carp/carp.sensing-flutter/packages/carp_audio_package/
  carp_survey_package:
    path: ../carp/carp.sensing-flutter/packages/carp_survey_package/
  carp_health_package:
    path: ../carp/carp.sensing-flutter/packages/carp_health_package/

  research_package:
    path: ../research.package/  
  cognition_package:
    path: ../cognition_package/  

  # due to this issue https://github.com/builttoroam/device_calendar/issues/586 
  device_calendar:
    git: https://github.com/bardram/device_calendar

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any 
  flutter_lints: any


# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/lungs.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo/cachet_logo.png
   - assets/images/carp_logo_example.png
   - assets/logo/lungs.png
   - assets/images/maui.png
   - assets/images/running.png
   - assets/images/audio.png
   - assets/images/cachet.png
   - assets/images/survey.png
   - assets/images/waving-hand.png
   - assets/images/very-sad.png
   - assets/images/sad.png
   - assets/images/ok.png
   - assets/images/happy.png
   - assets/images/very-happy.png
   - assets/lang/da.json
   - assets/lang/en.json

